version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./my-app/src:/opt/app/src
    environment:
      - NODE_ENV=development
      - APP_NAME=Hoi Dia Chu
    ports:
      - 6000:3000
      - 6001:3001
